add class Film, User, controllers, tests
pkingsbl/java-filmorate pull request #1
Opened 2022-10-03 00:25 UTC by pkingsbl

2022-10-03 17:43 UTC, Fleaman777 requested changes

2022-10-03 17:43 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/controller/FilmController.java
> +        }
сам if и его логику, можно было бы вынести в отдельный метод, 
так мы немного разделим ответственность, и в случае, если будут появлятся новые условия валидации, их будет проще добавить

2022-10-03 17:43 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/controller/FilmController.java
> +            throw new IOException("Фильм с id = " + film.getId() + " не найден!");
хорошо, что выбрасываешь исключение, но IOException здесь не очень подходит, т.к. привычней, это ислючение видеть в других случаях(запись данных в файл, потом, бд и пр.), а наш случай - это больше про то, что объекта не существует,
можно создать дополнительное кастомное исключение, например NotFoundException или использовать ValidationException, но просто передавать в него соответсвующее сообщение

2022-10-03 17:43 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/exception/ValidationException.java
> +public class ValidationException extends Throwable {
кастомные исключения лучше наследовать от RuntimeException, 
в таком случае, нам не нужно будет постоянно добавлять обработку потенциального исключения

2022-10-03 17:43 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/model/Film.java
> +    public Film(String name, String description, LocalDate releaseDate, int duration) {
что бы в ручную не создавать конструктор, можно так же использовать ломбок аннотации

2022-10-03 17:43 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/model/User.java
> +    @Email
здорово, что решила валидацию сделать через аннотации, 
это улучшает восприятие и качество кода

2022-10-03 17:43 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/FilmorateApplicationTest.java
> +class FilmorateApplicationTest {
обычно тесты на класс .....Application не создают, т.к. в нем почти никогда нет какой-либо логики, которую  нужно тестировать, 
а вот Controller классы (и др. похожие, узнаешь в будущих спринтах), тестируют как положено :) 

поэтому лучше сейчас создать 2 класса UserControllerTest и FilmControllerTest, и в них уже перенести соответствующие тесты

2022-10-03 17:43 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/FilmorateApplicationTest.java
> +    }
очень крутые тесты, Молодец! 

создаешь тестовый запрос (гет, пост, делит) и проверяишь, что вернул контроллер, 
а не просто вызываешь соответствующий метод контроллера с подходящими аргументами....

можно сказать, что сделала настоящие интеграционные тесты

2022-10-03 17:43 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/FilmorateApplicationTest.java
> +    void putValidFilmTest() throws Exception {
в назавании еще хорошо было бы указать, при каких условиях был проведен тест

2022-10-03 17:43 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/FilmorateApplicationTest.java
> +
может быть пропустил, но не увидел тест на проверку длины описания фильма

2022-10-05 20:21 UTC, pkingsbl commented on src/test/java/ru/yandex/practicum/FilmorateApplicationTest.java
> +
postFilmInvalidDescriptionTest

2022-10-06 17:53 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/FilmControllerTest.java
> +                , RandomString.make(201)
крутой ход, с тем что бы не создавать длинную строку вручную

2022-10-06 18:37 UTC, merged